myshell: myshell.c myshell_extracredit.c
	cc -Wall myshell.c -o myshell
	cc -Wall myshell_extracredit.c -o myshell_extracredit

clean:
	rm -f myshell myshell_extracredit myshell.o myshell_extracredit.o *~%